/* DO NOT EDIT THIS FILE - it is machine generated */
#include <iostream>
#include "com_example_jni_HelloJNI.h"

JNIEXPORT void JNICALL Java_com_example_jni_HelloJNI_sayHello(JNIEnv *env, jobject thisObj) {
	std::cout << "Hello World!\n";
	return;
}
